// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./components/App.vue')['default'];
    SmAccordion: typeof import('./components/SmAccordion/SmAccordion.vue')['default'];
    SmAccordionItem: typeof import('./components/SmAccordion/SmAccordionItem.vue')['default'];
    SmAccordionItemBody: typeof import('./components/SmAccordion/SmAccordionItemBody.vue')['default'];
    SmAccordionItemHeader: typeof import('./components/SmAccordion/SmAccordionItemHeader.vue')['default'];
    SmAlert: typeof import('./components/SmAlert/SmAlert.vue')['default'];
    SmAlertStack: typeof import('./components/SmAlert/SmAlertStack.vue')['default'];
    SmButton: typeof import('./components/SmButton/SmButton.vue')['default'];
    SmCard: typeof import('./components/SmCard/SmCard.vue')['default'];
    SmCheckbox: typeof import('./components/SmCheckbox/SmCheckbox.vue')['default'];
    SmDatepicker: typeof import('./components/SmDatepicker/SmDatepicker.vue')['default'];
    SmErrorList: typeof import('./components/SmErrorList/SmErrorList.vue')['default'];
    SmFileInput: typeof import('./components/SmFileInput/SmFileInput.vue')['default'];
    SmForm: typeof import('./components/SmForm/SmForm.vue')['default'];
    SmHint: typeof import('./components/SmHint/SmHint.vue')['default'];
    SmIcon: typeof import('./components/SmIcon/SmIcon.vue')['default'];
    SmInnerLoading: typeof import('./components/SmInnerLoading/SmInnerLoading.vue')['default'];
    SmInput: typeof import('./components/SmInput/SmInput.vue')['default'];
    SmLabel: typeof import('./components/SmLabel/SmLabel.vue')['default'];
    SmMarkupTable: typeof import('./components/SmMarkupTable/SmMarkupTable.vue')['default'];
    SmModal: typeof import('./components/SmModal/SmModal.vue')['default'];
    SmModalBody: typeof import('./components/SmModal/SmModalBody.vue')['default'];
    SmModalContent: typeof import('./components/SmModal/SmModalContent.vue')['default'];
    SmModalFooter: typeof import('./components/SmModal/SmModalFooter.vue')['default'];
    SmModalHeader: typeof import('./components/SmModal/SmModalHeader.vue')['default'];
    SmNameAvatar: typeof import('./components/SmNameAvatar/SmNameAvatar.vue')['default'];
    SmNumberInput: typeof import('./components/SmNumberInput/SmNumberInput.vue')['default'];
    SmPagination: typeof import('./components/SmPagination/SmPagination.vue')['default'];
    SmProgressBar: typeof import('./components/SmProgressBar/SmProgressBar.vue')['default'];
    SmProgressCircle: typeof import('./components/SmProgressCircle/SmProgressCircle.vue')['default'];
    SmRadio: typeof import('./components/SmRadio/SmRadio.vue')['default'];
    SmSelect: typeof import('./components/SmSelect/SmSelect.vue')['default'];
    SmSkeleton: typeof import('./components/SmSkeleton/SmSkeleton.vue')['default'];
    SmTabContent: typeof import('./components/SmTab/SmTabContent.vue')['default'];
    SmTable: typeof import('./components/SmTable/SmTable.vue')['default'];
    SmTabs: typeof import('./components/SmTab/SmTabs.vue')['default'];
    SmTabSelector: typeof import('./components/SmTab/SmTabSelector.vue')['default'];
    SmTabSelectors: typeof import('./components/SmTab/SmTabSelectors.vue')['default'];
    SmTextarea: typeof import('./components/SmTextarea/SmTextarea.vue')['default'];
    SmToggle: typeof import('./components/SmToggle/SmToggle.vue')['default'];
  }
}

export {};
