export const icons = [
  'accounting',
  'add-outline',
  'add',
  'arrow-left',
  'arrow-right',
  'banks',
  'stock',
  'caret-down',
  'caret-up-down',
  'caret-up',
  'categories',
  'close',
  'code',
  'contacts',
  'customize',
  'delete',
  'distributor',
  'docs-related',
  'edit',
  'email',
  'export',
  'help-outline',
  'help',
  'home',
  'import',
  'info-outline',
  'info',
  'input',
  'list',
  'loading',
  'lock',
  'menu',
  'minus',
  'more',
  'notification',
  'output',
  'payment-card',
  'payment-more',
  'payment',
  'payroll',
  'pdf',
  'phone',
  'play',
  'plus',
  'pos',
  'print',
  'product',
  'reports',
  'search',
  'settings',
  'social-dribbble',
  'social-facebook',
  'social-github',
  'social-instagram',
  'social-linkedin',
  'social-pinterest',
  'social-twitter',
  'social-vimeo',
  'social-whatsapp',
  'social-youtube',
  'success-outline',
  'success',
  'sync',
  'ticket',
  'user',
  'view-eye',
  'view-grid',
  'view-list',
  'premium',
  'chat-outline',
  'copy',
  'calendar-outline',
  'email-outline',
  'truck',
  'file-download',
  'xml',
  'alert-triangle',
  'alert-circle',
  'checklist',
  'building',
  'clipboard-list',
  'user-pencil',
  'lock-open',
  'bulb',
  'bulb-off',
  'send',
  'file-dots',
  'cash-out',
  'cash',
  'file-user',
  'file-dollar-out',
  'cash-in',
  'file-recurring-in',
  'user-plus',
  'user-off',
  'file-recurring-out',
  'file-dollar-in',
  'checks',
  'file-pencil',
  'grid-dots',
  'brand-mastercard',
  'photo',
  'puzzle',
  'circle-dots',
  'circle',
  'circle-half-2',
  'circle-off',
  'circle-filled',
  'open-link',
]

// TODO: cambiar a enum
// export enum Icon {
//   ACCOUNTING = "accounting",
//   ADD_OUTLINE = "add-outline",
//   ADD = "add",
//   ARROW_LEFT = "arrow-left",
//   ARROW_RIGHT = "arrow-right",
//   BANKS = "banks",
//   STOCKS = "stock",
//   CARET_DOWN = "caret-down",
//   CARET_UP_DOWN = "caret-up-down",
//   CARET_UP = "caret-up",
//   CATEGORIES = "categories",
//   CLOSE = "close",
//   CODE = "code",
//   CONTACTS = "contacts",
//   CUSTOMIZE = "customize",
//   DELETE = "delete",
//   HELP_OUTLINE = "help-outline",
//   HELP = "help",
//   HOME = "home",
//   IMPORT = "import",
//   INFO_OUTLINE = "info-outline",
//   INFO = "info",
//   INPUT = "input",
//   LIST = "list",
//   LOADING = "loading",
//   LOCK = "lock",
//   MENU = "menu",
//   MINUS = "minus",
//   MORE = "more",
//   NOTIFICATION = "notification",
//   OUTPUT = "output",
//   PAYMENT_CARD = "payment-card",
//   PAYMENT_MORE = "payment-more",
//   PAYMENT = "payment",
//   PAYROLL = "payroll",
//   PDF = "pdf",
//   PHONE = "phone",
//   PLAY = "play",
//   PLUS = "plus",
//   POS = "pos",
//   PRINT = "print",
//   PRODUCT = "product",
//   REPORTS = "reports",
//   SEARCH = "search",
//   SETTINGS = "settings",
//   DRIBBLE = "social-dribbble",
//   FACEBOOK = "social-facebook",
//   GITHUB = "social-github",
//   INSTAGRAM = "social-instagram",
//   LINKEDIN = "social-linkedin",
//   PINTEREST = "social-pinterest",
//   TWITTER = "social-twitter",
//   VIMEO = "social-vimeo",
//   WHATSAPP = "social-whatsapp",
//   YOUTUBE = "social-youtube",
//   SUCCESS_OUTLINE = "success-outline",
//   SUCCESS = "success",
//   SYNC = "sync",
//   TICKET = "ticket",
//   USER = "user",
//   VIEW_EYE = "view-eye",
//   VIEW_GRID = "view-grid",
//   VIEW_LIST = "view-list",
//   PREMIUM = "premium",
//   CHAT_OUTLINE = "chat-outline",
//   COPY = "copy",
//   CALENDAR_OUTLINE = "calendar-outline",
//   EMAIL_OUTLINE = "email-outline"
// }
